# Physical parameters
dim_num: 1
D: 1.0
α: 0.0
L: 256
N: 25600
T: 1.0
γ′: 1
ϵ: 0.0

# Simulation parameters
n_sweeps: 100

# Potential parameters
potential_type: "zero"
fluctuation_type: "independent-points-discrete"
potential_magnitude: 16

# Output parameters
save_dir: "saved_states"