# Physical parameters
dim_num = 1
D = 1.0                # diffusion coefficient
α = 0.3                # rate of tumbling 
L = 64                 # system size
N = 100*L               # number of particles
T = 1.0               # temperature   
β′ = 0.03

# Simulation parameters
n_sweeps = 100000

# Potential parameters
potential_type = "well"
potential_magnitude = 2
potential_fluc = "potential"

# Output parameters
save_dir = "saved_states"