#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  bash cluster_scripts/aggregate_managed_diffusive_1d_center_bond.sh \
      --run_id <managed_run_id> [options]

Options:
  --include_running       Include latest committed checkpoints of running replicas.
                          Default is stable-only: status must be idle.
  --min_tstats <int>      Minimum statistics_sample_count to include (default: 1)
  --aggregate_tag <tag>   Aggregate id tag suffix (default: managed_<timestamp>)
  -h, --help              Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/managed_diffusive_1d_center_bond_common.sh"
REPO_ROOT="$(managed_repo_root "${SCRIPT_DIR}")"
RUNNER_SCRIPT="${SCRIPT_DIR}/run_diffusive_no_activity_from_config.sh"

if [[ -z "${JULIA_SETUP_SCRIPT:-${CLUSTER_JULIA_SETUP_SCRIPT:-}}" && -f "/Local/ph_kafri/julia-1.7.2/bin/setup.sh" ]]; then
    export JULIA_SETUP_SCRIPT="/Local/ph_kafri/julia-1.7.2/bin/setup.sh"
fi

run_id=""
include_running="false"
min_tstats="1"
aggregate_tag=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --run_id) run_id="${2:-}"; shift 2 ;;
        --include_running) include_running="true"; shift 1 ;;
        --min_tstats) min_tstats="${2:-}"; shift 2 ;;
        --aggregate_tag) aggregate_tag="${2:-}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
    esac
done

if [[ -z "${run_id}" ]]; then
    echo "Missing --run_id." >&2
    usage
    exit 1
fi
managed_require_positive_int "min_tstats" "${min_tstats}"

run_id="$(managed_slugify "${run_id}")"
run_root="$(managed_run_root "${REPO_ROOT}" "${run_id}")"
run_spec="${run_root}/run_spec.yaml"
replicas_csv="${run_root}/replicas.csv"
lock_file="${run_root}/manager.lock"
if [[ ! -f "${run_spec}" || ! -f "${replicas_csv}" ]]; then
    echo "Managed run is not initialized: ${run_root}" >&2
    exit 1
fi
if [[ ! -f "${RUNNER_SCRIPT}" ]]; then
    echo "Missing runner script: ${RUNNER_SCRIPT}" >&2
    exit 1
fi

timestamp="$(managed_timestamp)"
if [[ -z "${aggregate_tag}" ]]; then
    aggregate_tag="managed_${timestamp}"
else
    aggregate_tag="$(managed_slugify "${aggregate_tag}")"
fi

aggregate_root="${run_root}/aggregates"
current_dir="${aggregate_root}/current"
work_dir="${aggregate_root}/work/${aggregate_tag}"
lineage_file="${aggregate_root}/lineage.csv"
state_list="${work_dir}/state_list.txt"
config_path="${work_dir}/aggregate_config.yaml"
mkdir -p "${current_dir}" "${work_dir}"

(
    flock 9
    : > "${state_list}"
    tail -n +2 "${replicas_csv}" | while IFS=, read -r rid _phase _elapsed stats latest _source _source_tag _claim status _updated; do
        [[ -n "${rid}" ]] || continue

        effective_stats="${stats}"
        effective_latest="${latest}"
        status_ok="false"
        if [[ "${status}" == "idle" || -z "${status}" ]]; then
            status_ok="true"
        elif [[ "${include_running}" == "true" && "${status}" == "running" ]]; then
            status_ok="true"
            meta_path="${run_root}/replicas/${rid}/current.meta"
            if [[ -f "${meta_path}" ]]; then
                meta_stats="$(awk 'index($0, "statistics_sweeps=") == 1 { print substr($0, 19); exit }' "${meta_path}")"
                meta_latest="$(awk 'index($0, "latest_state=") == 1 { print substr($0, 14); exit }' "${meta_path}")"
                [[ -n "${meta_stats}" ]] && effective_stats="${meta_stats}"
                [[ -n "${meta_latest}" ]] && effective_latest="${meta_latest}"
            fi
        fi

        if [[ "${status_ok}" == "true" && -n "${effective_latest}" &&
              "${effective_stats}" =~ ^[0-9]+$ ]] && (( effective_stats >= min_tstats )); then
            printf "%s\n" "${effective_latest}" >> "${state_list}"
        fi
    done
) 9>"${lock_file}"

state_count="$(wc -l < "${state_list}" | awk '{print $1}')"
if (( state_count <= 0 )); then
    echo "No managed replica states are eligible for aggregation." >&2
    echo "  run_id=${run_id}" >&2
    echo "  min_tstats=${min_tstats}" >&2
    echo "  include_running=${include_running}" >&2
    exit 1
fi

L="$(managed_yaml_value "${run_spec}" "L")"
rho="$(managed_yaml_value "${run_spec}" "rho0")"
D="$(managed_yaml_value "${run_spec}" "D")"
T="$(managed_yaml_value "${run_spec}" "T")"
force_strength="$(managed_yaml_value "${run_spec}" "forcing_magnitude")"
ffr="$(managed_yaml_value "${run_spec}" "ffr")"
force_strength="${force_strength:-1.0}"
ffr="${ffr:-1.0}"

cat > "${config_path}" <<EOF
# Generated by cluster_scripts/aggregate_managed_diffusive_1d_center_bond.sh
dim_num: 1
L: ${L}
ρ₀: ${rho}
D: ${D}
T: ${T}
γ: 0.0
n_sweeps: 1
warmup_sweeps: 0
performance_mode: true
description: "${run_id}_managed_aggregate"
int_type: "auto"
position_int_type: "auto"
keep_directional_densities: false

potential_type: "zero"
fluctuation_type: "no-fluctuation"
potential_magnitude: 0.0
ic: "aggregated"

forcing_type: "center_bond_x"
forcing_magnitude: ${force_strength}
ffr: ${ffr}
forcing_direction_flags: true
forcing_rate_scheme: "symmetric_normalized"
bond_pass_count_mode: "all_forcing_bonds"

show_times: []
save_times: []
save_dir: "${current_dir}"
progress_interval: 1000
EOF

echo "Aggregating managed diffusive 1D center-bond states:"
echo "  run_id=${run_id}"
echo "  states=${state_count}"
echo "  include_running=${include_running}"
echo "  state_list=${state_list}"
echo "  output_dir=${current_dir}"

"${RUNNER_SCRIPT}" "${config_path}" --aggregate_state_list "${state_list}" --save_tag "${aggregate_tag}" --performance_mode

latest_aggregate="$(find "${current_dir}" -maxdepth 1 -type f -name "*_id-aggregated_${aggregate_tag}.jld2" -printf '%T@ %p\n' 2>/dev/null | sort -nr | awk 'NR == 1 { $1=""; sub(/^ /, ""); print }')"
if [[ -z "${latest_aggregate}" ]]; then
    echo "Aggregation completed but could not locate the expected aggregate for tag ${aggregate_tag}." >&2
    exit 1
fi

if [[ ! -f "${lineage_file}" ]]; then
    echo "timestamp,aggregate_tag,state_count,min_tstats,include_running,state_list,aggregate_state" > "${lineage_file}"
fi
printf "%s,%s,%s,%s,%s,%s,%s\n" \
    "${timestamp}" "${aggregate_tag}" "${state_count}" "${min_tstats}" "${include_running}" "${state_list}" "${latest_aggregate}" \
    >> "${lineage_file}"

echo "Managed aggregation completed."
echo "  aggregate_state=${latest_aggregate}"
echo "  lineage=${lineage_file}"
